-- =============================================
-- Author:		<Author,,ADMIN>
-- Create date: <Create Date,, 08 Jun 2015>
-- Description:	<Description,,InsertOrUpdateEstablishment>
-- Call SP    :	InsertOrUpdateEstablishment
-- =============================================
CREATE PROCEDURE [dbo].[InsertOrUpdateEstablishment]
    @Id BIGINT,
    @GroupId BIGINT,
    @EstablishmentGroupId BIGINT,
    @EstablishmentName NVARCHAR(500),
    @GeographicalLocation NVARCHAR(500),
    @TimeOffSetId NVARCHAR(200),
    @TimeOffSet INT,
    @IncludedMonthlyReports INT,
    @UniqueSMSKeyword NVARCHAR(50),
    @CommonSMSKeyword NVARCHAR(50),
    @AutoResponseMessage NVARCHAR(300),
    @SendThankYouSMS BIT,
    @ThankYouMessage NVARCHAR(MAX),
    @SendSeenClientSMS BIT,
    @SeenClientAutoSMS NVARCHAR(500),
    @SendSeenClientEmail BIT,
    @SeenClientAutoEmail NVARCHAR(MAX),
    @SeenClientAutoNotification NVARCHAR(200),
    @SeenClientEscalationTime INT,
    @SeenClientSchedulerTime DATETIME,
    @SeenClientSchedulerTimeString NVARCHAR(50),
    @ShowIntroductoryOnMobi BIT,
    @IntroductoryMessage NVARCHAR(MAX),
    @EscalationEmails NVARCHAR(2000),
    @EscalationMobile NVARCHAR(2000),
    @EscalationTime INT,
    @EscalationSchedulerTime DATETIME,
    @EscalationSchedulerTimeString NVARCHAR(50),
    @EscalationSchedulerDay NVARCHAR(10),
    @FeedbackTimeSpan INT,
    @ShowSeenClientDetailsOnMobi BIT,
    @SendNotificationAlertForAll BIT,
    @SendFeedbackSMSAlert BIT,
    @FeedbackSMSAlert NVARCHAR(500),
    @SendFeedbackEmailAlert BIT,
    @FeedbackEmailAlert NVARCHAR(MAX),
    @FeedbackNotificationAlert NVARCHAR(250),
    @FeedbackRedirectURL NVARCHAR(500),
    @SeenClientEmailSubject NVARCHAR(MAX),
    @EscalationEmailSubject NVARCHAR(MAX),
    @FeedbackEmailSubject NVARCHAR(MAX),
    @FeedbackOnce BIT,
    @mobiFormDisplayFields NVARCHAR(MAX),
    @ThankyouPageMessage NVARCHAR(MAX),
    @UserId BIGINT,
    @PageId BIGINT,
    @SendOutNotificationAlertForAll BIT,
    @SendCaptureSMSAlert BIT,
    @CaptureSMSAlert NVARCHAR(500),
    @SendCaptureEmailAlert BIT,
    @CaptureEmailAlert NVARCHAR(MAX),
    @CaptureEmailSubject NVARCHAR(MAX),
    @CaptureNotificationAlert NVARCHAR(250),
    @OutEscalationEmailSubject NVARCHAR(MAX),
    @OutEscalationEmails NVARCHAR(2000),
    @OutEscalationMobile NVARCHAR(2000),
    @OutEscalationTime INT,
    @OutEscalationSchedulerTime DATETIME,
    @OutEscalationSchedulerTimeString NVARCHAR(50),
    @OutEscalationSchedulerDay NVARCHAR(10),
    @CommonIntroductoryMessage NVARCHAR(MAX),
    @ResolutionFeedbackQuestion NVARCHAR(MAX),
    @ResolutionFeedbackSMS NVARCHAR(2000),
    @ResolutionFeedbackEmail NVARCHAR(MAX),
    @ResolutionFeedbackEmailSubject NVARCHAR(50),
    @IsMultipleRouting BIT,
    @MultipleRoutingValue BIGINT,
    @ThankyoumessageforLessthanPI NVARCHAR(MAX),
    @ThankyoumessageforGretareThanPI NVARCHAR(MAX),
    @SendTransferFormEmail BIT,
    @TransferFormEmailSubject VARCHAR(500),
    @TransferFormEmail VARCHAR(2000),
    @SendTransferFormSMS BIT,
    @TransferFormSMS VARCHAR(500),
    @DisplayGroupKeyword BIT,
    @EstablishmentSequence INT,
    @DynamicSaveButtonText NVARCHAR(200),
    @HeaderImage NVARCHAR(MAX),
    @InEscalationOnce BIT,
    @OutEscalationOnce BIT,
    @isAdditionalCaptureEmail BIT,
    @additionalCaptureEmails NVARCHAR(2000),
    @additionalCaptureEmailSubject NVARCHAR(2000),
    @additionalCaptureEmailBody NVARCHAR(MAX),
    @isAdditionalCaptureSMS BIT,
    @additionalCaptureMobile NVARCHAR(500),
    @additionalCaptureSMSBody NVARCHAR(MAX),
    @isAdditionalFeedbackEmail BIT,
    @additionalFeedbackEmails NVARCHAR(2000),
    @additionalFeedbackEmailSubject NVARCHAR(2000),
    @additionalFeedbackEmailBody NVARCHAR(MAX),
    @isAdditionalFeedbackSMS BIT,
    @additionalFeedbackMobile NVARCHAR(500),
    @additionalFeedbackSMSBody NVARCHAR(MAX),
    @StatusIconEstablishment BIT,
    @ReminderCapture BIT = 0,
    @ReminderFeedback BIT = 0,
    @InitiatorAsRespondent BIT = 0,
    @ReleaseDateValidationMessage NVARCHAR(1000) = '',
    @MobiExpiredValidationMessage NVARCHAR(1000) = '',
    @CaptureReminderAlert NVARCHAR(1000) = '',
    @FeedBackReminderAlert NVARCHAR(1000) = '',
    @CaptureUnallocatedNotificationAlert NVARCHAR(2000),
    @HideClickHereButton BIT = 0,
    @MobiLoadingPageSplashImage VARCHAR(MAX) = NULL,
    @ThankYouPageSplashImage VARCHAR(MAX) = NULL
AS
BEGIN
    IF (@Id = 0)
    BEGIN
        INSERT INTO dbo.[Establishment]
        (
            [GroupId],
            [EstablishmentGroupId],
            [EstablishmentName],
            [GeographicalLocation],
            [TimeOffSetId],
            [TimeOffSet],
            [IncludedMonthlyReports],
            [UniqueSMSKeyword],
            [CommonSMSKeyword],
            [AutoResponseMessage],
            [SendThankYouSMS],
            [ThankYouMessage],
            [SendSeenClientSMS],
            [SeenClientAutoSMS],
            [SendSeenClientEmail],
            [SeenClientAutoEmail],
            [SeenClientAutoNotification],
            [SeenClientEscalationTime],
            [SeenClientSchedulerTime],
            [SeenClientSchedulerTimeString],
            [ShowIntroductoryOnMobi],
            [IntroductoryMessage],
            [EscalationEmails],
            [EscalationMobile],
            [EscalationTime],
            [EscalationSchedulerTime],
            [EscalationSchedulerTimeString],
            [EscalationSchedulerDay],
            [FeedbackTimeSpan],
            [ShowSeenClientDetailsOnMobi],
            [SendNotificationAlertForAll],
            [SendFeedbackSMSAlert],
            [FeedbackSMSAlert],
            [SendFeedbackEmailAlert],
            [FeedbackEmailAlert],
            [FeedbackNotificationAlert],
            [FeedbackRedirectURL],
            [SeenClientEmailSubject],
            [EscalationEmailSubject],
            [FeedbackEmailSubject],
            [FeedbackOnce],
            [mobiFormDisplayFields],
            [ThankyouPageMessage],
            SendOutNotificationAlertForAll,
            SendCaptureSMSAlert,
            CaptureSMSAlert,
            SendCaptureEmailAlert,
            CaptureEmailAlert,
            CaptureEmailSubject,
            CaptureNotificationAlert,
            CaptureUnallocatedNotificationAlert,
            OutEscalationEmailSubject,
            OutEscalationEmails,
            OutEscalationMobile,
            OutEscalationTime,
            OutEscalationSchedulerTime,
            OutEscalationSchedulerTimeString,
            OutEscalationSchedulerDay,
            CommonIntroductoryMessage,
            ResolutionFeedbackQuestion,
            ResolutionFeedbackSMS,
            ResolutionFeedbackEmail,
            ResolutionFeedbackEmailSubject,
            IsMultipleRouting,
            MultipleRoutingValue,
            ThankyoumessageforLessthanPI,
            ThankyoumessageforGretareThanPI,
            SendTransferFormEmail,
            TransferFormEmailSubject,
            TransferFormEmail,
            SendTransferFormSMS,
            TransferFormSMS,
            DisplayGroupKeyword,
            EstablishmentSequence,
            [CreatedOn],
            [CreatedBy],
            [IsDeleted],
            DynamicSaveButtonText,
            HeaderImage,
            InEscalationOnce,
            OutEscalationOnce,
            ISAdditionalCaptureEmail,
            AdditionalCaptureEmails,
            AdditionalCaptureEmailSubject,
            AdditionalCaptureEmailBody,
            ISAdditionalCaptureSMS,
            AdditionalCaptureMobile,
            AdditionalCaptureSMSBody,
            ISAdditionalFeedbackEmail,
            AdditionalFeedbackEmails,
            AdditionalFeedbackEmailSubject,
            AdditionalFeedbackEmailBody,
            ISAdditionalFeedbackSMS,
            AdditionalFeedbackMobile,
            AdditionalFeedbackSMSBody,
            StatusIconEstablishment,
            ReminderNotificationCapture,
            ReminderNotificationFeedback,
            InitiatorAsRespondent,
            ReleaseDateValidationMessage,
            MobiExpiredValidationMessage,
            CaptureReminderAlert,
            FeedBackReminderAlert,
            HideClickHereButton,
            MobiLoadingPageSplashImage,
            ThankYouPageSplashImage
        )
        VALUES
        (@GroupId, @EstablishmentGroupId, @EstablishmentName, @GeographicalLocation, @TimeOffSetId, @TimeOffSet,
         @IncludedMonthlyReports, @UniqueSMSKeyword, @CommonSMSKeyword, @AutoResponseMessage, @SendThankYouSMS,
         @ThankYouMessage, @SendSeenClientSMS, @SeenClientAutoSMS, @SendSeenClientEmail, @SeenClientAutoEmail,
         @SeenClientAutoNotification, @SeenClientEscalationTime, @SeenClientSchedulerTime,
         @SeenClientSchedulerTimeString, @ShowIntroductoryOnMobi, @IntroductoryMessage, @EscalationEmails,
         @EscalationMobile, @EscalationTime, @EscalationSchedulerTime, @EscalationSchedulerTimeString,
         @EscalationSchedulerDay, @FeedbackTimeSpan, @ShowSeenClientDetailsOnMobi, @SendNotificationAlertForAll,
         @SendFeedbackSMSAlert, @FeedbackSMSAlert, @SendFeedbackEmailAlert, @FeedbackEmailAlert,
         @FeedbackNotificationAlert, @FeedbackRedirectURL, @SeenClientEmailSubject, @EscalationEmailSubject,
         @FeedbackEmailSubject, @FeedbackOnce, @mobiFormDisplayFields, @ThankyouPageMessage,
         @SendOutNotificationAlertForAll, @SendCaptureSMSAlert, @CaptureSMSAlert, @SendCaptureEmailAlert,
         @CaptureEmailAlert, @CaptureEmailSubject, @CaptureNotificationAlert, @CaptureUnallocatedNotificationAlert,
         @OutEscalationEmailSubject, @OutEscalationEmails, @OutEscalationMobile, @OutEscalationTime,
         @OutEscalationSchedulerTime, @OutEscalationSchedulerTimeString, @OutEscalationSchedulerDay,
         @CommonIntroductoryMessage, @ResolutionFeedbackQuestion, @ResolutionFeedbackSMS, @ResolutionFeedbackEmail,
         @ResolutionFeedbackEmailSubject, @IsMultipleRouting, @MultipleRoutingValue, @ThankyoumessageforLessthanPI,
         @ThankyoumessageforGretareThanPI, @SendTransferFormEmail, @TransferFormEmailSubject, @TransferFormEmail,
         @SendTransferFormSMS, @TransferFormSMS, @DisplayGroupKeyword, @EstablishmentSequence, GETUTCDATE(), @UserId,
         0  , @DynamicSaveButtonText, @HeaderImage, @InEscalationOnce, @OutEscalationOnce, @isAdditionalCaptureEmail,
         @additionalCaptureEmails, @additionalCaptureEmailSubject, @additionalCaptureEmailBody,
         @isAdditionalCaptureSMS, @additionalCaptureMobile, @additionalCaptureSMSBody, @isAdditionalFeedbackEmail,
         @additionalFeedbackEmails, @additionalFeedbackEmailSubject, @additionalFeedbackEmailBody,
         @isAdditionalFeedbackSMS, @additionalFeedbackMobile, @additionalFeedbackSMSBody, @StatusIconEstablishment,
         @ReminderCapture, @ReminderFeedback, @InitiatorAsRespondent, @ReleaseDateValidationMessage,
         @MobiExpiredValidationMessage, @CaptureReminderAlert, @FeedBackReminderAlert, @HideClickHereButton,
         @MobiLoadingPageSplashImage, @ThankYouPageSplashImage);

        SELECT @Id = SCOPE_IDENTITY();

        INSERT INTO dbo.ActivityLog
        (
            UserId,
            PageId,
            AuditComments,
            TableName,
            RecordId,
            CreatedOn,
            CreatedBy,
            IsDeleted
        )
        VALUES
        (@UserId, @PageId, 'Insert record in table Establishment', 'Establishment', @Id, GETUTCDATE(), @UserId, 0);

        INSERT INTO dbo.[UserRolePermissions]
        (
            [PageID],
            [ActualID],
            [UserID],
            [CreatedOn],
            [CreatedBy],
            [UpdatedOn],
            [UpdatedBy],
            [DeletedOn],
            [DeletedBy],
            [IsDeleted]
        )
        VALUES
        (@PageId, @Id, @UserId, GETUTCDATE(), @UserId, NULL, NULL, NULL, NULL, 0);

    END;
    ELSE
    BEGIN
        UPDATE dbo.[Establishment]
        SET [GroupId] = @GroupId,
            [EstablishmentGroupId] = @EstablishmentGroupId,
            [EstablishmentName] = @EstablishmentName,
            [GeographicalLocation] = @GeographicalLocation,
            [TimeOffSetId] = @TimeOffSetId,
            [TimeOffSet] = @TimeOffSet,
            [IncludedMonthlyReports] = @IncludedMonthlyReports,
            [UniqueSMSKeyword] = @UniqueSMSKeyword,
            [CommonSMSKeyword] = @CommonSMSKeyword,
            [AutoResponseMessage] = @AutoResponseMessage,
            [SendThankYouSMS] = @SendThankYouSMS,
            [ThankYouMessage] = @ThankYouMessage,
            [SendSeenClientSMS] = @SendSeenClientSMS,
            [SeenClientAutoSMS] = @SeenClientAutoSMS,
            [SendSeenClientEmail] = @SendSeenClientEmail,
            [SeenClientAutoEmail] = @SeenClientAutoEmail,
            [SeenClientAutoNotification] = @SeenClientAutoNotification,
            [SeenClientEscalationTime] = @SeenClientEscalationTime,
            [SeenClientSchedulerTime] = @SeenClientSchedulerTime,
            [SeenClientSchedulerTimeString] = @SeenClientSchedulerTimeString,
            [ShowIntroductoryOnMobi] = @ShowIntroductoryOnMobi,
            [IntroductoryMessage] = @IntroductoryMessage,
            [EscalationEmails] = @EscalationEmails,
            [EscalationMobile] = @EscalationMobile,
            [EscalationTime] = @EscalationTime,
            [EscalationSchedulerTime] = @EscalationSchedulerTime,
            [EscalationSchedulerTimeString] = @EscalationSchedulerTimeString,
            [EscalationSchedulerDay] = @EscalationSchedulerDay,
            [FeedbackTimeSpan] = @FeedbackTimeSpan,
            [ShowSeenClientDetailsOnMobi] = @ShowSeenClientDetailsOnMobi,
            [SendNotificationAlertForAll] = @SendNotificationAlertForAll,
            [SendFeedbackSMSAlert] = @SendFeedbackSMSAlert,
            [FeedbackSMSAlert] = @FeedbackSMSAlert,
            [SendFeedbackEmailAlert] = @SendFeedbackEmailAlert,
            [FeedbackEmailAlert] = @FeedbackEmailAlert,
            [FeedbackNotificationAlert] = @FeedbackNotificationAlert,
            [FeedbackRedirectURL] = @FeedbackRedirectURL,
            [SeenClientEmailSubject] = @SeenClientEmailSubject,
            [EscalationEmailSubject] = @EscalationEmailSubject,
            [FeedbackEmailSubject] = @FeedbackEmailSubject,
            [FeedbackOnce] = @FeedbackOnce,
            [mobiFormDisplayFields] = @mobiFormDisplayFields,
            [ThankyouPageMessage] = @ThankyouPageMessage,
            SendOutNotificationAlertForAll = @SendOutNotificationAlertForAll,
            SendCaptureSMSAlert = @SendCaptureSMSAlert,
            CaptureSMSAlert = @CaptureSMSAlert,
            SendCaptureEmailAlert = @SendCaptureEmailAlert,
            CaptureEmailAlert = @CaptureEmailAlert,
            CaptureEmailSubject = @CaptureEmailSubject,
            CaptureNotificationAlert = @CaptureNotificationAlert,
            CaptureUnallocatedNotificationAlert = @CaptureUnallocatedNotificationAlert,
            OutEscalationEmailSubject = @OutEscalationEmailSubject,
            OutEscalationEmails = @OutEscalationEmails,
            OutEscalationMobile = @OutEscalationMobile,
            OutEscalationTime = @OutEscalationTime,
            OutEscalationSchedulerTime = @OutEscalationSchedulerTime,
            OutEscalationSchedulerTimeString = @OutEscalationSchedulerTimeString,
            OutEscalationSchedulerDay = @OutEscalationSchedulerDay,
            CommonIntroductoryMessage = @CommonIntroductoryMessage,
            ResolutionFeedbackQuestion = @ResolutionFeedbackQuestion,
            ResolutionFeedbackSMS = @ResolutionFeedbackSMS,
            ResolutionFeedbackEmail = @ResolutionFeedbackEmail,
            ResolutionFeedbackEmailSubject = @ResolutionFeedbackEmailSubject,
            IsMultipleRouting = @IsMultipleRouting,
            MultipleRoutingValue = @MultipleRoutingValue,
            ThankyoumessageforLessthanPI = @ThankyoumessageforLessthanPI,
            ThankyoumessageforGretareThanPI = @ThankyoumessageforGretareThanPI,
            SendTransferFormEmail = @SendTransferFormEmail,
            TransferFormEmailSubject = @TransferFormEmailSubject,
            TransferFormEmail = @TransferFormEmail,
            SendTransferFormSMS = @SendTransferFormSMS,
            TransferFormSMS = @TransferFormSMS,
            DisplayGroupKeyword = @DisplayGroupKeyword,
            EstablishmentSequence = @EstablishmentSequence,
            [UpdatedOn] = GETUTCDATE(),
            [UpdatedBy] = @UserId,
            DynamicSaveButtonText = @DynamicSaveButtonText,
            HeaderImage = @HeaderImage,
            InEscalationOnce = @InEscalationOnce,
            OutEscalationOnce = @OutEscalationOnce,
            ISAdditionalCaptureEmail = @isAdditionalCaptureEmail,
            AdditionalCaptureEmails = @additionalCaptureEmails,
            AdditionalCaptureEmailSubject = @additionalCaptureEmailSubject,
            AdditionalCaptureEmailBody = @additionalCaptureEmailBody,
            ISAdditionalCaptureSMS = @isAdditionalCaptureSMS,
            AdditionalCaptureMobile = @additionalCaptureMobile,
            AdditionalCaptureSMSBody = @additionalCaptureSMSBody,
            ISAdditionalFeedbackEmail = @isAdditionalFeedbackEmail,
            AdditionalFeedbackEmails = @additionalFeedbackEmails,
            AdditionalFeedbackEmailSubject = @additionalFeedbackEmailSubject,
            AdditionalFeedbackEmailBody = @additionalFeedbackEmailBody,
            ISAdditionalFeedbackSMS = @isAdditionalFeedbackSMS,
            AdditionalFeedbackMobile = @additionalFeedbackMobile,
            AdditionalFeedbackSMSBody = @additionalFeedbackSMSBody,
            StatusIconEstablishment = @StatusIconEstablishment,
            ReminderNotificationCapture = @ReminderCapture,
            ReminderNotificationFeedback = @ReminderFeedback,
            InitiatorAsRespondent = @InitiatorAsRespondent,
            ReleaseDateValidationMessage = @ReleaseDateValidationMessage,
            MobiExpiredValidationMessage = @MobiExpiredValidationMessage,
            CaptureReminderAlert = @CaptureReminderAlert,
            FeedBackReminderAlert = @FeedBackReminderAlert,
            HideClickHereButton = @HideClickHereButton,
            MobiLoadingPageSplashImage = @MobiLoadingPageSplashImage,
            ThankYouPageSplashImage = @ThankYouPageSplashImage
        WHERE [Id] = @Id;
        INSERT INTO dbo.ActivityLog
        (
            UserId,
            PageId,
            AuditComments,
            TableName,
            RecordId,
            CreatedOn,
            CreatedBy,
            IsDeleted
        )
        VALUES
        (@UserId, @PageId, 'Update record in table Establishment', 'Establishment', @Id, GETUTCDATE(), @UserId, 0);
    END;
    SELECT ISNULL(@Id, 0) AS InsertedId;
END;
