CREATE PROCEDURE [dbo].[PB_Proc_Masslift_Fact_SalesStack]
AS
BEGIN
	set NoCount On;

	Declare @Desc Varchar(200)
	Exec dbo.PB_Log_Insert 'Masslift_Fact_SalesStack','Masslift_Fact_SalesStack Start','Masslift'

	Truncate table dbo.Masslift_Fact_SalesStack

	
	INSERT INTO Masslift_Fact_SalesStack(EstablishmentName,CapturedDate,ReferenceNo,
IsPositive,Status,PI,
UserId,UserName,Longitude,Latitude,

[Salesmen name: ],
[Customer ],
[Serial number ],
[Model ],
[Mast ],
[Delivery address ],
[Contact person on ],
[Contact number ],
[Bank / finance con],
[Bank Contact number ],
[Expected date of d],
[Client Chose ],
[MF Costing sheet ],
[MF Signed quote ],
[MF Masslift credit ap],
[MF Site Survey ],
[MF Financial Survey ],
[MF AIM ],
[MF RV Percentage ],
[MF RV percentage (%)],
[MF Bank approval],
[MF Bank Name],
[MF Signed RV addendum],
[MF Signed ownership ],
[MF Rental with owner],
[MF Rental No Ownershi],
[OP Costing sheet ],
[OP Signed quote ],
[OP Site survey],
[OP Financial survey],
[OP Purchase order ],
[OP Existing client ],
[OP AIM ],
[OP PMA],
[CF Costing sheet ],
[CF Signed quote ],
[CF Masslift credit ap],
[CF Site survey ],
[CF Financial survey ],
[CF AIM],
[CF RV percentage (%)],
[CF Return unit fleet ],
[CF Rental without own],
[CF Bank Name ],
[CF Rental with owners],
[BB Costing sheet ],
[BB Signed quote ],
[BB Masslift credit ap],
[BB Site survey ],
[BB Financial survey ],
[BB AIM],
[BB RV percentage (%)],
[BB Bank approval ],
[BB Bank name ],
[BB Signed ownership ],
[BB Signed MRA],
[BB Sunlyn agreement],
[MB Costing sheet ],
[MB Signed quote ],
[MB Financial survey ],
[MB Site survey ],
[MB Masslift credit ap],
[MB Signed MRA ],
[Model: ],
[S/Shift ],
[Forks (mm)],
[Tyres (If not stan],
[FMX],
[Contact for FMX ],
[Email for FMX cont],
[TXP transmission p],
[Donaldson filtrati],
[PTX purifier ],
[Spray (if not stan],
[Transaction ],
[Machine Serial number ],
[Quantity ],
[Type ],
[Amount],
[Invoice ],
[Date Paid ],
[If other, please s],[Is this a new or e],
[ORDER INTAKE BY TR],
[Branch],
[Dealer ],
[New or used ],ResponseDate,
CustomerName,CustomerSurname,CustomerCompany,CustomerEmail,CustomerMobile,
[Your title],
[Do you approve?],
 [If not, please comment],
[Is your signature required for sign off?],
[Selling Price (ZAR)],
[Cost Price (ZAR)],
[Gross Profit (ZAR)],
[Gross Profit %],
[Your signature] )
	SELECT EstablishmentName,CapturedDate,ReferenceNo,
IsPositive,Status,PI,
UserId,UserName,Longitude,Latitude,

[Salesmen name: ],
[Customer ],
[Serial number ],
[Model ],
[Mast ],
[Delivery address ],
[Contact person on ],
[Contact number ],
[Bank / finance con],
[Bank Contact number ],
[Expected date of d],
[Client Chose ],
[MF Costing sheet ],
[MF Signed quote ],
[MF Masslift credit ap],
[MF Site Survey ],
[MF Financial Survey ],
[MF AIM ],
[MF RV Percentage ],
[MF RV percentage (%)],
[MF Bank approval],
[MF Bank Name],
[MF Signed RV addendum],
[MF Signed ownership ],
[MF Rental with owner],
[MF Rental No Ownershi],
[OP Costing sheet ],
[OP Signed quote ],
[OP Site survey],
[OP Financial survey],
[OP Purchase order ],
[OP Existing client ],
[OP AIM ],
[OP PMA],
[CF Costing sheet ],
[CF Signed quote ],
[CF Masslift credit ap],
[CF Site survey ],
[CF Financial survey ],
[CF AIM],
[CF RV percentage (%)],
[CF Return unit fleet ],
[CF Rental without own],
[CF Bank Name ],
[CF Rental with owners],
[BB Costing sheet ],
[BB Signed quote ],
[BB Masslift credit ap],
[BB Site survey ],
[BB Financial survey ],
[BB AIM],
[BB RV percentage (%)],
[BB Bank approval ],
[BB Bank name ],
[BB Signed ownership ],
[BB Signed MRA],
[BB Sunlyn agreement],
[MB Costing sheet ],
[MB Signed quote ],
[MB Financial survey ],
[MB Site survey ],
[MB Masslift credit ap],
[MB Signed MRA ],
[Model: ],
[S/Shift ],
[Forks (mm)],
[Tyres (If not stan],
[FMX],
[Contact for FMX ],
[Email for FMX cont],
[TXP transmission p],
[Donaldson filtrati],
[PTX purifier ],
[Spray (if not stan],
[Transaction ],
[Machine Serial number ],
[Quantity ],
[Type ],
[Amount],
[Invoice ],
[Date Paid ],
[If other, please s],[Is this a new or e],
[ORDER INTAKE BY TR],
[Branch],
[Dealer ],
[New or used ],ResponseDate,
CustomerName,CustomerSurname,CustomerCompany,CustomerEmail,CustomerMobile,
[Your title],
[Do you approve?],
 [If not, please comment],
[Is your signature required for sign off?],
[Selling Price (ZAR)],
[Cost Price (ZAR)],
[Gross Profit (ZAR)],
[Gross Profit %],
[Your signature] 

	 FROM [PB_VW_Masslift_Fact_SalesStack]

	SELECT @Desc = 'Masslift_Fact_SalesStack Completed.( '+  CONVERT(VARCHAR,COUNT(1)) + ' ) Records Inserted'  FROM dbo.Masslift_Fact_SalesStack(NOLOCK) 
	EXEC dbo.PB_Log_Insert 'Masslift_Fact_SalesStack',@Desc,'Masslift'

	SET NOCOUNT OFF;
END
