CREATE VIEW dbo.VW_TEST_ESTABLISHMENTLIST
AS

WITH CTE AS 
(
    SELECT Total,RowNum,Id,Name,ContactId,IsGroup,TotalRows,
        ROW_NUMBER() OVER (
            PARTITION BY Id
            ORDER BY CreatedOn DESC) AS ROWNUM1
	FROM TEST_ESTABLISHMENTLIST
)
SELECT * FROM CTE WHERE ROWNUM1 = 1

